# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 642a3b36a6fdf8a2e9022aeab302fd1bc072ae8f5b6ae661cdab5030e2fdbcae0273baccc5aea475a88ce2c51ae31ab810581f6c4a6c1d79e232756a52ca2fc3

test:
  secret_key_base: a18b9ce70f4175915a173167baa50a5e7e5d2c814d65f2e77e1cf24ed5fbb08943899147064237c665df815bfd1c435ac340c2dcd109b99a0a4c3c730e90c505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
